name: spark-test

on: [push, pull_request]

jobs:

    spark:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v3
          with:
            python-version: '3.10'

        - uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: temurin
        
        - uses: vemonet/setup-spark@v1
          with:
            spark-version: '3.1.2'
            hadoop-version: '3'
        
        - run: spark-submit test.py
    